//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_DinhQuocDat_2210900139.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int MaThanhToan { get; set; }
        public int MaDonHang { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public decimal SoTienThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
